name: Deploy Admin Backend to Hugging Face Space

on:
  push:
    branches:
      - main   # agar branch master hai to master likho

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🤗 Sync to Hugging Face (Admin)
        uses: huggingface/hub-sync@v0.1.0
        with:
          github_repo_id: kaushalp8095/Quantifyre_Iris_SuperAdmin_Backend
          huggingface_repo_id: KaushalPatel/quantifyre-admin-backend   # 👈 apna HF space naam
          repo_type: space
          hf_token: ${{ secrets.HFA_TOKEN }}   # 👈 admin ka token
